# Generated by Django 4.2.29 on 2026-03-19 04:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='código')),
                ('token_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='hash del token')),
                ('status', models.CharField(choices=[('created', 'Creada'), ('sent', 'Enviada'), ('used', 'Usada'), ('cancelled', 'Anulada')], db_index=True, default='created', max_length=20, verbose_name='estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de uso')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de anulación')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='graduates.graduate', verbose_name='graduando')),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fingerprint', models.CharField(blank=True, max_length=16, verbose_name='huella del token')),
                ('result', models.CharField(choices=[('valid', 'Válida'), ('used', 'Usada'), ('cancelled', 'Anulada'), ('not_found', 'No encontrada'), ('error', 'Error')], db_index=True, max_length=20, verbose_name='resultado')),
                ('validated_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de validación')),
                ('marked_as_used', models.BooleanField(default=False, verbose_name='marcada como usada')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='invitations.invitation', verbose_name='invitación')),
            ],
            options={
                'verbose_name': 'registro de validación',
                'verbose_name_plural': 'registros de validación',
                'ordering': ('-validated_at',),
            },
        ),
    ]
