# Generated by Django 4.2.29 on 2026-06-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceremonies', '0001_initial'),
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_modificacion', verbose_name='fecha de modificacion')),
                ('code', models.CharField(db_column='codigo', max_length=32, verbose_name='codigo')),
                ('name', models.CharField(db_column='nombre', max_length=100, verbose_name='nombre')),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=255, verbose_name='descripcion')),
                ('ceremony', models.ForeignKey(db_column='ceremonia_id', on_delete=django.db.models.deletion.PROTECT, related_name='access_points', to='ceremonies.ceremony', verbose_name='ceremonia')),
            ],
            options={
                'verbose_name': 'punto de acceso',
                'verbose_name_plural': 'puntos de acceso',
                'db_table': '"invitaciones_grado"."punto_acceso"',
                'ordering': ('ceremony', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_modificacion', verbose_name='fecha de modificacion')),
                ('public_id', models.UUIDField(db_column='identificador_publico', default=uuid.uuid4, editable=False, verbose_name='identificador publico')),
                ('sequence_number', models.PositiveSmallIntegerField(db_column='numero_invitacion', verbose_name='numero de invitacion')),
                ('code', models.CharField(db_column='codigo', editable=False, max_length=64, verbose_name='codigo')),
                ('token_version', models.PositiveSmallIntegerField(db_column='version_token', default=1, verbose_name='version del token')),
                ('status', models.CharField(choices=[('created', 'Creada'), ('sent', 'Enviada'), ('used', 'Usada'), ('cancelled', 'Anulada')], db_column='estado', default='created', max_length=20, verbose_name='estado')),
                ('sent_at', models.DateTimeField(blank=True, db_column='fecha_envio', null=True, verbose_name='fecha de envio')),
                ('used_at', models.DateTimeField(blank=True, db_column='fecha_uso', null=True, verbose_name='fecha de uso')),
                ('cancelled_at', models.DateTimeField(blank=True, db_column='fecha_anulacion', null=True, verbose_name='fecha de anulacion')),
                ('used_device_label', models.CharField(blank=True, db_column='etiqueta_dispositivo_uso', max_length=100, verbose_name='etiqueta del dispositivo')),
                ('used_from_ip', models.GenericIPAddressField(blank=True, db_column='ip_validacion_exitosa', null=True, verbose_name='IP de validacion exitosa')),
                ('graduate', models.ForeignKey(db_column='graduando_id', on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='graduates.graduate', verbose_name='graduando')),
                ('used_access_point', models.ForeignKey(blank=True, db_column='punto_acceso_uso_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitations', to='invitations.accesspoint', verbose_name='punto de acceso')),
                ('used_by', models.ForeignKey(blank=True, db_column='usuario_validador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitations', to=settings.AUTH_USER_MODEL, verbose_name='validada por')),
            ],
            options={
                'verbose_name': 'invitacion',
                'verbose_name_plural': 'invitaciones',
                'db_table': '"invitaciones_grado"."invitacion"',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_modificacion', verbose_name='fecha de modificacion')),
                ('token_fingerprint', models.CharField(blank=True, db_column='huella_token', max_length=16, verbose_name='huella del token')),
                ('device_label', models.CharField(blank=True, db_column='etiqueta_dispositivo', max_length=100, verbose_name='etiqueta del dispositivo')),
                ('result', models.CharField(choices=[('valid', 'Valida'), ('used', 'Usada'), ('cancelled', 'Anulada'), ('invalid_token', 'Token invalido'), ('not_found', 'No encontrada'), ('error', 'Error')], db_column='resultado', max_length=20, verbose_name='resultado')),
                ('validated_at', models.DateTimeField(auto_now_add=True, db_column='fecha_validacion', verbose_name='fecha de validacion')),
                ('marked_as_used', models.BooleanField(db_column='marcada_como_usada', default=False, verbose_name='marcada como usada')),
                ('source_ip', models.GenericIPAddressField(blank=True, db_column='direccion_ip', null=True, verbose_name='direccion IP')),
                ('user_agent', models.TextField(blank=True, db_column='agente_usuario', verbose_name='user agent')),
                ('access_point', models.ForeignKey(blank=True, db_column='punto_acceso_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='invitations.accesspoint', verbose_name='punto de acceso')),
                ('invitation', models.ForeignKey(blank=True, db_column='invitacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='invitations.invitation', verbose_name='invitacion')),
                ('validator', models.ForeignKey(blank=True, db_column='usuario_validador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_validation_logs', to=settings.AUTH_USER_MODEL, verbose_name='validado por')),
            ],
            options={
                'verbose_name': 'registro de validacion',
                'verbose_name_plural': 'registros de validacion',
                'db_table': '"invitaciones_grado"."registro_validacion"',
                'ordering': ('-validated_at',),
                'indexes': [models.Index(fields=['token_fingerprint'], name='idx_vlog_huella'), models.Index(fields=['invitation', 'validated_at'], name='idx_vlog_inv_fval'), models.Index(fields=['result', 'validated_at'], name='idx_vlog_res_fval'), models.Index(fields=['validator', 'validated_at'], name='idx_vlog_usr_fval'), models.Index(fields=['access_point', 'validated_at'], name='idx_vlog_pacc_fval')],
            },
        ),
        migrations.AddConstraint(
            model_name='validationlog',
            constraint=models.CheckConstraint(check=models.Q(('marked_as_used', False), ('invitation__isnull', False), _connector='OR'), name='ck_vlog_uso_req_inv'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['graduate', 'status'], name='idx_inv_grad_est'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status', 'used_at'], name='idx_inv_est_fuso'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(('sequence_number__gte', 1)), name='ck_inv_numero'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(('token_version__gte', 1)), name='ck_inv_version'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('public_id',), name='uq_inv_pubid'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_inv_codigo'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('graduate', 'sequence_number'), name='uq_inv_grad_num'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'used'), ('used_at__isnull', False), ('cancelled_at__isnull', True)), models.Q(('status', 'cancelled'), ('cancelled_at__isnull', False), ('used_at__isnull', True)), models.Q(('status__in', ['created', 'sent']), ('used_at__isnull', True), ('cancelled_at__isnull', True)), _connector='OR'), name='ck_inv_estado_fech'),
        ),
        migrations.AddIndex(
            model_name='accesspoint',
            index=models.Index(fields=['ceremony', 'is_active'], name='idx_ptacc_cer_act'),
        ),
        migrations.AddConstraint(
            model_name='accesspoint',
            constraint=models.UniqueConstraint(fields=('ceremony', 'code'), name='uq_ptacc_cer_codigo'),
        ),
    ]
