# Generated by Django 4.2.29 on 2026-03-19 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ceremonies", "0002_domain_refinement"),
        ("graduates", "0002_domain_refinement"),
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, verbose_name="código")),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="activo"),
                ),
                (
                    "ceremony",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_points",
                        to="ceremonies.ceremony",
                        verbose_name="ceremonia",
                    ),
                ),
            ],
            options={
                "verbose_name": "punto de acceso",
                "verbose_name_plural": "puntos de acceso",
                "ordering": ("ceremony", "name"),
            },
        ),
        migrations.AddField(
            model_name="invitation",
            name="sequence_number",
            field=models.PositiveSmallIntegerField(
                default=1,
                verbose_name="número de invitación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="token_version",
            field=models.PositiveSmallIntegerField(
                default=1,
                verbose_name="versión del token",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="used_access_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_invitations",
                to="invitations.accesspoint",
                verbose_name="punto de acceso",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="validada por",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="used_device_label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="etiqueta del dispositivo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="used_from_ip",
            field=models.GenericIPAddressField(
                blank=True,
                null=True,
                verbose_name="IP de validación exitosa",
            ),
        ),
        migrations.AddField(
            model_name="validationlog",
            name="access_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validation_logs",
                to="invitations.accesspoint",
                verbose_name="punto de acceso",
            ),
        ),
        migrations.AddField(
            model_name="validationlog",
            name="device_label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="etiqueta del dispositivo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="validationlog",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitation_validation_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="validado por",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="code",
            field=models.CharField(
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="código",
            ),
        ),
        migrations.AlterField(
            model_name="validationlog",
            name="result",
            field=models.CharField(
                choices=[
                    ("valid", "Válida"),
                    ("used", "Usada"),
                    ("cancelled", "Anulada"),
                    ("invalid_token", "Token inválido"),
                    ("not_found", "No encontrada"),
                    ("error", "Error"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="resultado",
            ),
        ),
        migrations.AlterField(
            model_name="validationlog",
            name="token_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=16,
                verbose_name="huella del token",
            ),
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="token_hash",
        ),
        migrations.AddConstraint(
            model_name="accesspoint",
            constraint=models.UniqueConstraint(
                fields=("ceremony", "code"),
                name="unique_access_point_code_per_ceremony",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                check=models.Q(("sequence_number__gte", 1)),
                name="invitation_sequence_number_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                check=models.Q(("token_version__gte", 1)),
                name="invitation_token_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                fields=("graduate", "sequence_number"),
                name="unique_invitation_sequence_per_graduate",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                check=(
                    (
                        models.Q(("status", "used"))
                        & models.Q(("used_at__isnull", False))
                        & models.Q(("cancelled_at__isnull", True))
                    )
                    | (
                        models.Q(("status", "cancelled"))
                        & models.Q(("cancelled_at__isnull", False))
                        & models.Q(("used_at__isnull", True))
                    )
                    | (
                        models.Q(("status__in", ["created", "sent"]))
                        & models.Q(("used_at__isnull", True))
                        & models.Q(("cancelled_at__isnull", True))
                    )
                ),
                name="invitation_status_dates_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationlog",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(("marked_as_used", False))
                    | models.Q(("invitation__isnull", False))
                ),
                name="validation_log_marked_used_requires_invitation",
            ),
        ),
        migrations.AddIndex(
            model_name="accesspoint",
            index=models.Index(
                fields=["ceremony", "is_active"],
                name="accpt_cer_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["graduate", "status"],
                name="invitation_graduate_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["status", "used_at"],
                name="invitation_status_used_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationlog",
            index=models.Index(
                fields=["invitation", "validated_at"],
                name="vlog_inv_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationlog",
            index=models.Index(
                fields=["result", "validated_at"],
                name="vlog_result_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationlog",
            index=models.Index(
                fields=["validator", "validated_at"],
                name="vlog_user_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationlog",
            index=models.Index(
                fields=["access_point", "validated_at"],
                name="vlog_ap_time_idx",
            ),
        ),
    ]
