# Generated by Django 4.2.29 on 2026-04-10 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("wso2", "WSO2")],
                        max_length=20,
                        verbose_name="proveedor",
                    ),
                ),
                ("issuer", models.CharField(max_length=255, verbose_name="issuer")),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="correo electronico",
                    ),
                ),
                (
                    "username_claim",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="claim de usuario",
                    ),
                ),
                (
                    "claims_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="snapshot de claims",
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="ultimo login",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "identidad externa",
                "verbose_name_plural": "identidades externas",
                "ordering": ("provider", "issuer", "subject"),
            },
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(
                fields=["provider", "email"],
                name="extid_provider_email_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "issuer", "subject"),
                name="unique_external_identity_provider_issuer_subject",
            ),
        ),
    ]
