# Generated by Django 4.2.29 on 2026-06-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_modificacion', verbose_name='fecha de modificacion')),
                ('provider', models.CharField(choices=[('wso2', 'WSO2')], db_column='proveedor', max_length=20, verbose_name='proveedor')),
                ('issuer', models.CharField(db_column='issuer', max_length=255, verbose_name='issuer')),
                ('subject', models.CharField(db_column='subject', max_length=255, verbose_name='subject')),
                ('email', models.EmailField(blank=True, db_column='correo_electronico', max_length=254, verbose_name='correo electronico')),
                ('username_claim', models.CharField(blank=True, db_column='claim_usuario', max_length=255, verbose_name='claim de usuario')),
                ('claims_snapshot', models.JSONField(blank=True, db_column='snapshot_claims', default=dict, verbose_name='snapshot de claims')),
                ('last_login_at', models.DateTimeField(blank=True, db_column='fecha_ultimo_inicio_sesion', null=True, verbose_name='ultimo login')),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'identidad externa',
                'verbose_name_plural': 'identidades externas',
                'db_table': '"invitaciones_grado"."identidad_externa"',
                'ordering': ('provider', 'issuer', 'subject'),
                'indexes': [models.Index(fields=['provider', 'email'], name='idx_extid_prov_email')],
            },
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'issuer', 'subject'), name='uq_extid_prov_iss_sub'),
        ),
    ]
