# Generated by Django 4.2.29 on 2026-06-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceremonies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateImportBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_modificacion', verbose_name='fecha de modificacion')),
                ('source_filename', models.CharField(db_column='archivo_fuente', max_length=255, verbose_name='archivo fuente')),
                ('file_sha256', models.CharField(db_column='archivo_sha256', max_length=64, verbose_name='sha256')),
                ('status', models.CharField(choices=[('validated', 'Validado'), ('confirmed', 'Confirmado'), ('failed', 'Fallido')], db_column='estado', default='validated', max_length=20, verbose_name='estado')),
                ('rows_total', models.PositiveIntegerField(db_column='filas_leidas', default=0, verbose_name='filas leidas')),
                ('rows_valid', models.PositiveIntegerField(db_column='filas_validas', default=0, verbose_name='filas validas')),
                ('rows_error', models.PositiveIntegerField(db_column='filas_error', default=0, verbose_name='filas con error')),
                ('graduates_created', models.PositiveIntegerField(db_column='graduandos_creados', default=0, verbose_name='graduandos creados')),
                ('graduates_updated', models.PositiveIntegerField(db_column='graduandos_actualizados', default=0, verbose_name='graduandos actualizados')),
                ('invitations_created', models.PositiveIntegerField(db_column='invitaciones_creadas', default=0, verbose_name='invitaciones creadas')),
                ('preview_payload', models.JSONField(blank=True, db_column='resultado_validacion', default=dict, verbose_name='resultado de validacion')),
                ('failure_message', models.TextField(blank=True, db_column='detalle_fallo', verbose_name='detalle de fallo')),
                ('confirmed_at', models.DateTimeField(blank=True, db_column='fecha_confirmacion', null=True, verbose_name='fecha de confirmacion')),
                ('ceremony', models.ForeignKey(db_column='ceremonia_id', on_delete=django.db.models.deletion.PROTECT, related_name='graduate_import_batches', to='ceremonies.ceremony', verbose_name='ceremonia')),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='usuario_confirmacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_graduate_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='usuario_cargue_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_graduate_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
            ],
            options={
                'verbose_name': 'lote de importacion de graduandos',
                'verbose_name_plural': 'lotes de importacion de graduandos',
                'db_table': '"invitaciones_grado"."lote_importacion_graduando"',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['ceremony', 'status', 'created_at'], name='idx_limp_cer_est_fcre')],
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_modificacion', verbose_name='fecha de modificacion')),
                ('document_type', models.CharField(blank=True, db_column='tipo_documento', max_length=20, verbose_name='tipo de documento')),
                ('student_code', models.CharField(blank=True, db_column='codigo_estudiantil', max_length=32, verbose_name='codigo estudiantil')),
                ('document_number', models.CharField(db_column='numero_documento', max_length=32, verbose_name='documento')),
                ('full_name', models.CharField(db_column='nombre_completo', max_length=255, verbose_name='nombre completo')),
                ('academic_program', models.CharField(db_column='programa_academico', max_length=255, verbose_name='programa academico')),
                ('email', models.EmailField(blank=True, db_column='correo_electronico', max_length=254, verbose_name='correo electronico')),
                ('invitation_quota', models.PositiveSmallIntegerField(db_column='cantidad_invitaciones', default=3, verbose_name='cantidad de invitaciones')),
                ('ceremony', models.ForeignKey(db_column='ceremonia_id', on_delete=django.db.models.deletion.PROTECT, related_name='graduates', to='ceremonies.ceremony', verbose_name='ceremonia')),
            ],
            options={
                'verbose_name': 'graduando',
                'verbose_name_plural': 'graduandos',
                'db_table': '"invitaciones_grado"."graduando"',
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['document_number'], name='idx_grad_numdoc'), models.Index(fields=['student_code'], name='idx_grad_codest'), models.Index(fields=['ceremony', 'full_name'], name='idx_grad_cer_nom')],
            },
        ),
        migrations.AddConstraint(
            model_name='graduate',
            constraint=models.CheckConstraint(check=models.Q(('invitation_quota__gte', 0)), name='ck_graduando_cant_inv'),
        ),
        migrations.AddConstraint(
            model_name='graduate',
            constraint=models.UniqueConstraint(fields=('ceremony', 'document_number'), name='uq_grad_cer_numdoc'),
        ),
        migrations.AddConstraint(
            model_name='graduate',
            constraint=models.UniqueConstraint(condition=models.Q(('student_code', ''), _negated=True), fields=('ceremony', 'student_code'), name='uq_grad_cer_codest'),
        ),
    ]
