# Generated by Django 4.2.29 on 2026-03-19 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceremonies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_code', models.CharField(blank=True, max_length=32, verbose_name='código estudiantil')),
                ('document_number', models.CharField(max_length=32, verbose_name='documento')),
                ('full_name', models.CharField(max_length=255, verbose_name='nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('invitation_quota', models.PositiveSmallIntegerField(default=2, verbose_name='cantidad de invitaciones')),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduates', to='ceremonies.ceremony', verbose_name='ceremonia')),
            ],
            options={
                'verbose_name': 'graduando',
                'verbose_name_plural': 'graduandos',
                'ordering': ('full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='graduate',
            constraint=models.UniqueConstraint(fields=('ceremony', 'document_number'), name='unique_graduate_document_per_ceremony'),
        ),
    ]
