# Generated by Django 4.2.29 on 2026-03-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graduates", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="graduate",
            constraint=models.CheckConstraint(
                check=models.Q(("invitation_quota__gte", 0)),
                name="graduate_invitation_quota_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="graduate",
            index=models.Index(
                fields=["document_number"],
                name="graduate_document_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graduate",
            index=models.Index(
                fields=["ceremony", "full_name"],
                name="graduate_ceremony_name_idx",
            ),
        ),
    ]
