# Generated by Django 4.2.29 on 2026-03-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graduates", "0002_domain_refinement"),
    ]

    operations = [
        migrations.AddField(
            model_name="graduate",
            name="academic_program",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="programa académico",
            ),
            preserve_default=False,
        ),
    ]
