# Generated by Django 4.2.29 on 2026-03-27 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceremonies', '0002_domain_refinement'),
        ('graduates', '0003_academic_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_filename', models.CharField(max_length=255, verbose_name='archivo fuente')),
                ('file_sha256', models.CharField(max_length=64, verbose_name='sha256')),
                ('status', models.CharField(choices=[('validated', 'Validado'), ('confirmed', 'Confirmado'), ('failed', 'Fallido')], db_index=True, default='validated', max_length=20, verbose_name='estado')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='filas leidas')),
                ('rows_valid', models.PositiveIntegerField(default=0, verbose_name='filas validas')),
                ('rows_error', models.PositiveIntegerField(default=0, verbose_name='filas con error')),
                ('graduates_created', models.PositiveIntegerField(default=0, verbose_name='graduandos creados')),
                ('graduates_updated', models.PositiveIntegerField(default=0, verbose_name='graduandos actualizados')),
                ('invitations_created', models.PositiveIntegerField(default=0, verbose_name='invitaciones creadas')),
                ('preview_payload', models.JSONField(blank=True, default=dict, verbose_name='resultado de validacion')),
                ('failure_message', models.TextField(blank=True, verbose_name='detalle de fallo')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de confirmacion')),
            ],
            options={
                'verbose_name': 'lote de importacion de graduandos',
                'verbose_name_plural': 'lotes de importacion de graduandos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='graduate',
            name='document_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='academic_program',
            field=models.CharField(max_length=255, verbose_name='programa academico'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='invitation_quota',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='cantidad de invitaciones'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='student_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='codigo estudiantil'),
        ),
        migrations.AddIndex(
            model_name='graduate',
            index=models.Index(fields=['student_code'], name='graduate_student_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='graduate',
            constraint=models.UniqueConstraint(condition=models.Q(('student_code', ''), _negated=True), fields=('ceremony', 'student_code'), name='unique_graduate_student_code_per_ceremony'),
        ),
        migrations.AddField(
            model_name='graduateimportbatch',
            name='ceremony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduate_import_batches', to='ceremonies.ceremony', verbose_name='ceremonia'),
        ),
        migrations.AddField(
            model_name='graduateimportbatch',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_graduate_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por'),
        ),
        migrations.AddField(
            model_name='graduateimportbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_graduate_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='cargado por'),
        ),
        migrations.AddIndex(
            model_name='graduateimportbatch',
            index=models.Index(fields=['ceremony', 'status', 'created_at'], name='gradimp_ceremony_status_idx'),
        ),
    ]
