# Generated by Django 4.2.29 on 2026-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_modificacion', verbose_name='fecha de modificacion')),
                ('code', models.CharField(db_column='codigo', max_length=32, verbose_name='codigo')),
                ('name', models.CharField(db_column='nombre', max_length=255, verbose_name='nombre')),
                ('scheduled_at', models.DateTimeField(db_column='fecha_programada', verbose_name='fecha y hora')),
                ('venue', models.CharField(db_column='lugar', max_length=255, verbose_name='lugar')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], db_column='estado', default='draft', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'ceremonia',
                'verbose_name_plural': 'ceremonias',
                'db_table': '"invitaciones_grado"."ceremonia"',
                'ordering': ('scheduled_at', 'name'),
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='idx_ceremonia_est_fprog')],
            },
        ),
        migrations.AddConstraint(
            model_name='ceremony',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_ceremonia_codigo'),
        ),
    ]
