# Generated by Django 4.2.29 on 2026-03-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('scheduled_at', models.DateTimeField(verbose_name='fecha y hora')),
                ('venue', models.CharField(max_length=255, verbose_name='lugar')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'ceremonia',
                'verbose_name_plural': 'ceremonias',
                'ordering': ('scheduled_at', 'name'),
            },
        ),
    ]
