# Generated by Django 4.2.29 on 2026-03-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceremonies", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ceremony",
            index=models.Index(
                fields=["status", "scheduled_at"],
                name="ceremony_status_schedule_idx",
            ),
        ),
    ]
