-- DDL institucional generado desde migraciones Django
-- Alcance: esquema invitaciones_grado y tablas propias del dominio
-- Generado: 2026-06-04T14:41:29.735286+00:00
-- Nota: este artefacto asume que las tablas tecnicas de Django
-- (auth_*, django_*, sessions, admin_*) se gestionan aparte.

-- core.0001_initial
BEGIN;
--
-- Raw SQL operation
--
CREATE SCHEMA IF NOT EXISTS "invitaciones_grado";
COMMIT;

-- ceremonies.0001_initial
BEGIN;
--
-- Create model Ceremony
--
CREATE TABLE "invitaciones_grado"."ceremonia" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "codigo" varchar(32) NOT NULL, "nombre" varchar(255) NOT NULL, "fecha_programada" timestamp with time zone NOT NULL, "lugar" varchar(255) NOT NULL, "estado" varchar(20) NOT NULL);
--
-- Create constraint uq_ceremonia_codigo on model ceremony
--
ALTER TABLE "invitaciones_grado"."ceremonia" ADD CONSTRAINT "uq_ceremonia_codigo" UNIQUE ("codigo");
CREATE INDEX "idx_ceremonia_est_fprog" ON "invitaciones_grado"."ceremonia" ("estado", "fecha_programada");
COMMIT;

-- accounts.0001_initial
BEGIN;
--
-- Create model ExternalIdentity
--
CREATE TABLE "invitaciones_grado"."identidad_externa" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "proveedor" varchar(20) NOT NULL, "issuer" varchar(255) NOT NULL, "subject" varchar(255) NOT NULL, "correo_electronico" varchar(254) NOT NULL, "claim_usuario" varchar(255) NOT NULL, "snapshot_claims" jsonb NOT NULL, "fecha_ultimo_inicio_sesion" timestamp with time zone NULL, "usuario_id" integer NOT NULL);
--
-- Create constraint uq_extid_prov_iss_sub on model externalidentity
--
ALTER TABLE "invitaciones_grado"."identidad_externa" ADD CONSTRAINT "uq_extid_prov_iss_sub" UNIQUE ("proveedor", "issuer", "subject");
ALTER TABLE "invitaciones_grado"."identidad_externa" ADD CONSTRAINT "identidad_externa_usuario_id_dd284d88_fk_auth_user_id" FOREIGN KEY ("usuario_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "identidad_externa_usuario_id_dd284d88" ON "invitaciones_grado"."identidad_externa" ("usuario_id");
CREATE INDEX "idx_extid_prov_email" ON "invitaciones_grado"."identidad_externa" ("proveedor", "correo_electronico");
COMMIT;

-- graduates.0001_initial
BEGIN;
--
-- Create model GraduateImportBatch
--
CREATE TABLE "invitaciones_grado"."lote_importacion_graduando" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "archivo_fuente" varchar(255) NOT NULL, "archivo_sha256" varchar(64) NOT NULL, "estado" varchar(20) NOT NULL, "filas_leidas" integer NOT NULL CHECK ("filas_leidas" >= 0), "filas_validas" integer NOT NULL CHECK ("filas_validas" >= 0), "filas_error" integer NOT NULL CHECK ("filas_error" >= 0), "graduandos_creados" integer NOT NULL CHECK ("graduandos_creados" >= 0), "graduandos_actualizados" integer NOT NULL CHECK ("graduandos_actualizados" >= 0), "invitaciones_creadas" integer NOT NULL CHECK ("invitaciones_creadas" >= 0), "resultado_validacion" jsonb NOT NULL, "detalle_fallo" text NOT NULL, "fecha_confirmacion" timestamp with time zone NULL, "ceremonia_id" integer NOT NULL, "usuario_confirmacion_id" integer NULL, "usuario_cargue_id" integer NULL);
--
-- Create model Graduate
--
CREATE TABLE "invitaciones_grado"."graduando" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "tipo_documento" varchar(20) NOT NULL, "codigo_estudiantil" varchar(32) NOT NULL, "numero_documento" varchar(32) NOT NULL, "nombre_completo" varchar(255) NOT NULL, "programa_academico" varchar(255) NOT NULL, "correo_electronico" varchar(254) NOT NULL, "cantidad_invitaciones" smallint NOT NULL CHECK ("cantidad_invitaciones" >= 0), "ceremonia_id" integer NOT NULL);
--
-- Create constraint ck_graduando_cant_inv on model graduate
--
ALTER TABLE "invitaciones_grado"."graduando" ADD CONSTRAINT "ck_graduando_cant_inv" CHECK ("cantidad_invitaciones" >= 0);
--
-- Create constraint uq_grad_cer_numdoc on model graduate
--
ALTER TABLE "invitaciones_grado"."graduando" ADD CONSTRAINT "uq_grad_cer_numdoc" UNIQUE ("ceremonia_id", "numero_documento");
--
-- Create constraint uq_grad_cer_codest on model graduate
--
CREATE UNIQUE INDEX "uq_grad_cer_codest" ON "invitaciones_grado"."graduando" ("ceremonia_id", "codigo_estudiantil") WHERE NOT ("codigo_estudiantil" = '');
ALTER TABLE "invitaciones_grado"."lote_importacion_graduando" ADD CONSTRAINT "lote_importacion_gra_ceremonia_id_2c39c916_fk_ceremonia" FOREIGN KEY ("ceremonia_id") REFERENCES "invitaciones_grado"."ceremonia" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."lote_importacion_graduando" ADD CONSTRAINT "lote_importacion_gra_usuario_confirmacion_a39f66f3_fk_auth_user" FOREIGN KEY ("usuario_confirmacion_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."lote_importacion_graduando" ADD CONSTRAINT "lote_importacion_gra_usuario_cargue_id_d4d06651_fk_auth_user" FOREIGN KEY ("usuario_cargue_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "lote_importacion_graduando_ceremonia_id_2c39c916" ON "invitaciones_grado"."lote_importacion_graduando" ("ceremonia_id");
CREATE INDEX "lote_importacion_graduando_usuario_confirmacion_id_a39f66f3" ON "invitaciones_grado"."lote_importacion_graduando" ("usuario_confirmacion_id");
CREATE INDEX "lote_importacion_graduando_usuario_cargue_id_d4d06651" ON "invitaciones_grado"."lote_importacion_graduando" ("usuario_cargue_id");
CREATE INDEX "idx_limp_cer_est_fcre" ON "invitaciones_grado"."lote_importacion_graduando" ("ceremonia_id", "estado", "fecha_creacion");
ALTER TABLE "invitaciones_grado"."graduando" ADD CONSTRAINT "graduando_ceremonia_id_982f8793_fk_ceremonia_id" FOREIGN KEY ("ceremonia_id") REFERENCES "invitaciones_grado"."ceremonia" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "graduando_ceremonia_id_982f8793" ON "invitaciones_grado"."graduando" ("ceremonia_id");
CREATE INDEX "idx_grad_numdoc" ON "invitaciones_grado"."graduando" ("numero_documento");
CREATE INDEX "idx_grad_codest" ON "invitaciones_grado"."graduando" ("codigo_estudiantil");
CREATE INDEX "idx_grad_cer_nom" ON "invitaciones_grado"."graduando" ("ceremonia_id", "nombre_completo");
COMMIT;

-- invitations.0001_initial
BEGIN;
--
-- Create model AccessPoint
--
CREATE TABLE "invitaciones_grado"."punto_acceso" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "codigo" varchar(32) NOT NULL, "nombre" varchar(100) NOT NULL, "descripcion" varchar(255) NOT NULL, "ceremonia_id" integer NOT NULL);
--
-- Create model Invitation
--
CREATE TABLE "invitaciones_grado"."invitacion" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "identificador_publico" uuid NOT NULL, "numero_invitacion" smallint NOT NULL CHECK ("numero_invitacion" >= 0), "codigo" varchar(64) NOT NULL, "version_token" smallint NOT NULL CHECK ("version_token" >= 0), "estado" varchar(20) NOT NULL, "fecha_envio" timestamp with time zone NULL, "fecha_uso" timestamp with time zone NULL, "fecha_anulacion" timestamp with time zone NULL, "etiqueta_dispositivo_uso" varchar(100) NOT NULL, "ip_validacion_exitosa" inet NULL, "graduando_id" integer NOT NULL, "punto_acceso_uso_id" integer NULL, "usuario_validador_id" integer NULL);
--
-- Create model ValidationLog
--
CREATE TABLE "invitaciones_grado"."registro_validacion" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "huella_token" varchar(16) NOT NULL, "etiqueta_dispositivo" varchar(100) NOT NULL, "resultado" varchar(20) NOT NULL, "fecha_validacion" timestamp with time zone NOT NULL, "marcada_como_usada" boolean NOT NULL, "direccion_ip" inet NULL, "agente_usuario" text NOT NULL, "punto_acceso_id" integer NULL, "invitacion_id" integer NULL, "usuario_validador_id" integer NULL);
--
-- Create constraint ck_vlog_uso_req_inv on model validationlog
--
ALTER TABLE "invitaciones_grado"."registro_validacion" ADD CONSTRAINT "ck_vlog_uso_req_inv" CHECK ((NOT "marcada_como_usada" OR "invitacion_id" IS NOT NULL));
--
-- Create index idx_inv_grad_est on field(s) graduate, status of model invitation
--
CREATE INDEX "idx_inv_grad_est" ON "invitaciones_grado"."invitacion" ("graduando_id", "estado");
--
-- Create index idx_inv_est_fuso on field(s) status, used_at of model invitation
--
CREATE INDEX "idx_inv_est_fuso" ON "invitaciones_grado"."invitacion" ("estado", "fecha_uso");
--
-- Create constraint ck_inv_numero on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "ck_inv_numero" CHECK ("numero_invitacion" >= 1);
--
-- Create constraint ck_inv_version on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "ck_inv_version" CHECK ("version_token" >= 1);
--
-- Create constraint uq_inv_pubid on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "uq_inv_pubid" UNIQUE ("identificador_publico");
--
-- Create constraint uq_inv_codigo on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "uq_inv_codigo" UNIQUE ("codigo");
--
-- Create constraint uq_inv_grad_num on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "uq_inv_grad_num" UNIQUE ("graduando_id", "numero_invitacion");
--
-- Create constraint ck_inv_estado_fech on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "ck_inv_estado_fech" CHECK ((("estado" = 'used' AND "fecha_uso" IS NOT NULL AND "fecha_anulacion" IS NULL) OR ("estado" = 'cancelled' AND "fecha_anulacion" IS NOT NULL AND "fecha_uso" IS NULL) OR ("estado" IN ('created', 'sent') AND "fecha_uso" IS NULL AND "fecha_anulacion" IS NULL)));
--
-- Create index idx_ptacc_cer_act on field(s) ceremony, is_active of model accesspoint
--
CREATE INDEX "idx_ptacc_cer_act" ON "invitaciones_grado"."punto_acceso" ("ceremonia_id", "activo");
--
-- Create constraint uq_ptacc_cer_codigo on model accesspoint
--
ALTER TABLE "invitaciones_grado"."punto_acceso" ADD CONSTRAINT "uq_ptacc_cer_codigo" UNIQUE ("ceremonia_id", "codigo");
ALTER TABLE "invitaciones_grado"."punto_acceso" ADD CONSTRAINT "punto_acceso_ceremonia_id_72aeed4e_fk_ceremonia_id" FOREIGN KEY ("ceremonia_id") REFERENCES "invitaciones_grado"."ceremonia" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "punto_acceso_ceremonia_id_72aeed4e" ON "invitaciones_grado"."punto_acceso" ("ceremonia_id");
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "invitacion_graduando_id_70ffb4f4_fk_graduando_id" FOREIGN KEY ("graduando_id") REFERENCES "invitaciones_grado"."graduando" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "invitacion_punto_acceso_uso_id_76e8fc29_fk_punto_acceso_id" FOREIGN KEY ("punto_acceso_uso_id") REFERENCES "invitaciones_grado"."punto_acceso" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "invitacion_usuario_validador_id_bf8517ce_fk_auth_user_id" FOREIGN KEY ("usuario_validador_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "invitacion_graduando_id_70ffb4f4" ON "invitaciones_grado"."invitacion" ("graduando_id");
CREATE INDEX "invitacion_punto_acceso_uso_id_76e8fc29" ON "invitaciones_grado"."invitacion" ("punto_acceso_uso_id");
CREATE INDEX "invitacion_usuario_validador_id_bf8517ce" ON "invitaciones_grado"."invitacion" ("usuario_validador_id");
ALTER TABLE "invitaciones_grado"."registro_validacion" ADD CONSTRAINT "registro_validacion_punto_acceso_id_9ef1b57a_fk_punto_acceso_id" FOREIGN KEY ("punto_acceso_id") REFERENCES "invitaciones_grado"."punto_acceso" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."registro_validacion" ADD CONSTRAINT "registro_validacion_invitacion_id_31d99b9c_fk_invitacion_id" FOREIGN KEY ("invitacion_id") REFERENCES "invitaciones_grado"."invitacion" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."registro_validacion" ADD CONSTRAINT "registro_validacion_usuario_validador_id_4b24951c_fk_auth_user" FOREIGN KEY ("usuario_validador_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "registro_validacion_punto_acceso_id_9ef1b57a" ON "invitaciones_grado"."registro_validacion" ("punto_acceso_id");
CREATE INDEX "registro_validacion_invitacion_id_31d99b9c" ON "invitaciones_grado"."registro_validacion" ("invitacion_id");
CREATE INDEX "registro_validacion_usuario_validador_id_4b24951c" ON "invitaciones_grado"."registro_validacion" ("usuario_validador_id");
CREATE INDEX "idx_vlog_huella" ON "invitaciones_grado"."registro_validacion" ("huella_token");
CREATE INDEX "idx_vlog_inv_fval" ON "invitaciones_grado"."registro_validacion" ("invitacion_id", "fecha_validacion");
CREATE INDEX "idx_vlog_res_fval" ON "invitaciones_grado"."registro_validacion" ("resultado", "fecha_validacion");
CREATE INDEX "idx_vlog_usr_fval" ON "invitaciones_grado"."registro_validacion" ("usuario_validador_id", "fecha_validacion");
CREATE INDEX "idx_vlog_pacc_fval" ON "invitaciones_grado"."registro_validacion" ("punto_acceso_id", "fecha_validacion");
COMMIT;
