from io import StringIO
from pathlib import Path

from django.apps import apps
from django.conf import settings
from django.contrib.auth import get_permission_codename
from django.core.management import call_command
from django.core.management.base import BaseCommand
from django.db.migrations.loader import MigrationLoader
from django.utils import timezone

from apps.core.schema import (
    INSTITUTIONAL_SCHEMA,
    create_schema_sql,
    set_search_path_sql,
)


RUNTIME_DDL_APPS = (
    "contenttypes",
    "auth",
    "admin",
    "sessions",
    "core",
    "ceremonies",
    "accounts",
    "graduates",
    "invitations",
)

TECHNICAL_TABLES = (
    "auth_group",
    "auth_group_permissions",
    "auth_permission",
    "auth_user",
    "auth_user_groups",
    "auth_user_user_permissions",
    "django_admin_log",
    "django_content_type",
    "django_session",
)


class Command(BaseCommand):
    help = (
        "Exporta el SQL necesario para levantar una base PostgreSQL funcional "
        "para el proyecto."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            default="docs/ddl/invitaciones_grado.sql",
            help="Ruta del archivo SQL a generar.",
        )

    def handle(self, *args, **options):
        output_path = Path(options["output"]).expanduser()
        if not output_path.is_absolute():
            output_path = Path(settings.BASE_DIR) / output_path

        output_path.parent.mkdir(parents=True, exist_ok=True)

        migration_plan = self._get_runtime_migration_plan()
        generated_at = timezone.now()

        sections: list[str] = [
            "-- SQL de bootstrap generado desde migraciones Django",
            "-- Alcance: tablas tecnicas del framework + dominio en invitaciones_grado",
            f"-- Generado: {generated_at.isoformat()}",
            "-- Destino: base PostgreSQL nueva para ejecutar el proyecto.",
            create_schema_sql(),
            set_search_path_sql(),
            "",
        ]

        for app_label, migration_name in migration_plan:
            if (app_label, migration_name) == ("core", "0001_initial"):
                continue
            buffer = StringIO()
            call_command(
                "sqlmigrate",
                app_label,
                migration_name,
                stdout=buffer,
                no_color=True,
                verbosity=0,
            )
            sql = self._qualify_runtime_sql(buffer.getvalue().strip())
            sections.extend(
                [
                    f"-- {app_label}.{migration_name}",
                    sql,
                    "",
                ]
            )

        sections.extend(self._render_django_migrations_sql(migration_plan, generated_at))
        sections.extend(self._render_seed_metadata_sql())

        output_path.write_text("\n".join(sections).rstrip() + "\n", encoding="utf-8")
        self.stdout.write(
            self.style.SUCCESS(f"DDL institucional exportado a {output_path}")
        )

    def _get_runtime_migration_plan(self) -> list[tuple[str, str]]:
        loader = MigrationLoader(None, ignore_no_migrations=True)
        ordered_nodes: list[tuple[str, str]] = []
        seen_nodes: set[tuple[str, str]] = set()

        for app_label in RUNTIME_DDL_APPS:
            for leaf_node in loader.graph.leaf_nodes(app_label):
                for node in loader.graph.forwards_plan(leaf_node):
                    if node in seen_nodes:
                        continue
                    seen_nodes.add(node)
                    ordered_nodes.append(node)

        return ordered_nodes

    def _render_django_migrations_sql(
        self,
        migration_plan: list[tuple[str, str]],
        generated_at,
    ) -> list[str]:
        applied_at = generated_at.isoformat()
        rows = [
            (app_label, migration_name, applied_at)
            for app_label, migration_name in migration_plan
        ]

        return [
            "-- django_migrations",
            "BEGIN;",
            (
                f"CREATE TABLE IF NOT EXISTS {self._qualified_table_name('django_migrations')} ("
                '"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, '
                '"app" varchar(255) NOT NULL, '
                '"name" varchar(255) NOT NULL, '
                '"applied" timestamp with time zone NOT NULL'
                ");"
            ),
            self._render_insert(
                self._qualified_table_name("django_migrations"),
                ("app", "name", "applied"),
                rows,
            ),
            self._render_setval(self._qualified_table_name("django_migrations")),
            "COMMIT;",
            "",
        ]

    def _render_seed_metadata_sql(self) -> list[str]:
        content_type_rows, content_type_map = self._build_content_type_rows()
        permission_rows = self._build_permission_rows(content_type_map)

        return [
            "-- Metadatos base de Django",
            "BEGIN;",
            self._render_insert(
                self._qualified_table_name("django_content_type"),
                ("id", "app_label", "model"),
                content_type_rows,
            ),
            self._render_setval(self._qualified_table_name("django_content_type")),
            self._render_insert(
                self._qualified_table_name("auth_permission"),
                ("id", "name", "content_type_id", "codename"),
                permission_rows,
            ),
            self._render_setval(self._qualified_table_name("auth_permission")),
            "COMMIT;",
            "",
        ]

    def _build_content_type_rows(self) -> tuple[list[tuple[int, str, str]], dict[tuple[str, str], int]]:
        rows: list[tuple[int, str, str]] = []
        content_type_map: dict[tuple[str, str], int] = {}
        next_id = 1

        for app_label in RUNTIME_DDL_APPS:
            app_config = apps.get_app_config(app_label)
            if not app_config.models_module:
                continue

            models_in_app = sorted(
                app_config.get_models(),
                key=lambda model: model._meta.model_name,
            )
            for model in models_in_app:
                key = (app_label, model._meta.model_name)
                content_type_map[key] = next_id
                rows.append((next_id, app_label, model._meta.model_name))
                next_id += 1

        return rows, content_type_map

    def _build_permission_rows(
        self,
        content_type_map: dict[tuple[str, str], int],
    ) -> list[tuple[int, str, int, str]]:
        rows: list[tuple[int, str, int, str]] = []
        next_id = 1

        for app_label in RUNTIME_DDL_APPS:
            app_config = apps.get_app_config(app_label)
            if not app_config.models_module:
                continue

            models_in_app = sorted(
                app_config.get_models(),
                key=lambda model: model._meta.model_name,
            )
            for model in models_in_app:
                opts = model._meta
                content_type_id = content_type_map[(app_label, opts.model_name)]
                permissions = [
                    *[
                        (
                            f"Can {action} {opts.verbose_name_raw}",
                            get_permission_codename(action, opts),
                        )
                        for action in opts.default_permissions
                    ],
                    *[(name, codename) for codename, name in opts.permissions],
                ]
                for permission_name, codename in permissions:
                    rows.append((next_id, permission_name, content_type_id, codename))
                    next_id += 1

        return rows

    def _render_insert(
        self,
        table_name: str,
        columns: tuple[str, ...],
        rows: list[tuple],
    ) -> str:
        if not rows:
            return f"-- Sin filas para {table_name}"

        rendered_rows = ",\n".join(
            f"    ({', '.join(self._sql_literal(value) for value in row)})"
            for row in rows
        )
        rendered_columns = ", ".join(f'"{column}"' for column in columns)
        return f"INSERT INTO {table_name} ({rendered_columns})\nVALUES\n{rendered_rows};"

    def _render_setval(self, table_name: str) -> str:
        return (
            "SELECT setval("
            f"pg_get_serial_sequence('{table_name}', 'id'), "
            f'COALESCE((SELECT MAX("id") FROM {table_name}), 1), '
            "true"
            ");"
        )

    def _qualified_table_name(self, table_name: str) -> str:
        return f'"{INSTITUTIONAL_SCHEMA}"."{table_name}"'

    def _qualify_runtime_sql(self, sql: str) -> str:
        for table_name in TECHNICAL_TABLES:
            sql = sql.replace(
                f'"{table_name}"',
                self._qualified_table_name(table_name),
            )
        return sql

    def _sql_literal(self, value) -> str:
        if value is None:
            return "NULL"
        if isinstance(value, bool):
            return "TRUE" if value else "FALSE"
        if isinstance(value, (int, float)):
            return str(value)
        text = str(value).replace("'", "''")
        return f"'{text}'"
