-- SQL de bootstrap generado desde migraciones Django
-- Alcance: tablas tecnicas del framework + dominio en invitaciones_grado
-- Generado: 2026-06-10T20:52:07.846858+00:00
-- Destino: base PostgreSQL nueva para ejecutar el proyecto.
CREATE SCHEMA IF NOT EXISTS "invitaciones_grado";
SET search_path TO invitaciones_grado, public;

-- contenttypes.0001_initial
BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "invitaciones_grado"."django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "invitaciones_grado"."django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
COMMIT;

-- contenttypes.0002_remove_content_type_name
BEGIN;
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "invitaciones_grado"."django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "invitaciones_grado"."django_content_type" DROP COLUMN "name" CASCADE;
COMMIT;

-- auth.0001_initial
BEGIN;
--
-- Create model Permission
--
CREATE TABLE "invitaciones_grado"."auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "invitaciones_grado"."auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "invitaciones_grado"."auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
CREATE TABLE "invitaciones_grado"."auth_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NOT NULL, "is_superuser" boolean NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "invitaciones_grado"."auth_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "invitaciones_grado"."auth_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "permission_id" integer NOT NULL);
ALTER TABLE "invitaciones_grado"."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "invitaciones_grado"."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "invitaciones_grado"."django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "invitaciones_grado"."auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "invitaciones_grado"."auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "invitaciones_grado"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "invitaciones_grado"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "invitaciones_grado"."auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "invitaciones_grado"."auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "invitaciones_grado"."auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "invitaciones_grado"."auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_username_6821ab7c_like" ON "invitaciones_grado"."auth_user" ("username" varchar_pattern_ops);
ALTER TABLE "invitaciones_grado"."auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "invitaciones_grado"."auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "invitaciones_grado"."auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "invitaciones_grado"."auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "invitaciones_grado"."auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "invitaciones_grado"."auth_user_groups" ("group_id");
ALTER TABLE "invitaciones_grado"."auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "invitaciones_grado"."auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "invitaciones_grado"."auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "invitaciones_grado"."auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "invitaciones_grado"."auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "invitaciones_grado"."auth_user_user_permissions" ("permission_id");
COMMIT;

-- auth.0002_alter_permission_name_max_length
BEGIN;
--
-- Alter field name on permission
--
ALTER TABLE "invitaciones_grado"."auth_permission" ALTER COLUMN "name" TYPE varchar(255);
COMMIT;

-- auth.0003_alter_user_email_max_length
BEGIN;
--
-- Alter field email on user
--
ALTER TABLE "invitaciones_grado"."auth_user" ALTER COLUMN "email" TYPE varchar(254);
COMMIT;

-- auth.0004_alter_user_username_opts
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- auth.0005_alter_user_last_login_null
BEGIN;
--
-- Alter field last_login on user
--
ALTER TABLE "invitaciones_grado"."auth_user" ALTER COLUMN "last_login" DROP NOT NULL;
COMMIT;

-- auth.0006_require_contenttypes_0002


-- auth.0007_alter_validators_add_error_messages
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- auth.0008_alter_user_username_max_length
BEGIN;
--
-- Alter field username on user
--
ALTER TABLE "invitaciones_grado"."auth_user" ALTER COLUMN "username" TYPE varchar(150);
COMMIT;

-- auth.0009_alter_user_last_name_max_length
BEGIN;
--
-- Alter field last_name on user
--
ALTER TABLE "invitaciones_grado"."auth_user" ALTER COLUMN "last_name" TYPE varchar(150);
COMMIT;

-- auth.0010_alter_group_name_max_length
BEGIN;
--
-- Alter field name on group
--
ALTER TABLE "invitaciones_grado"."auth_group" ALTER COLUMN "name" TYPE varchar(150);
COMMIT;

-- auth.0011_update_proxy_permissions
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- auth.0012_alter_user_first_name_max_length
BEGIN;
--
-- Alter field first_name on user
--
ALTER TABLE "invitaciones_grado"."auth_user" ALTER COLUMN "first_name" TYPE varchar(150);
COMMIT;

-- admin.0001_initial
BEGIN;
--
-- Create model LogEntry
--
CREATE TABLE "invitaciones_grado"."django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" integer NOT NULL);
ALTER TABLE "invitaciones_grado"."django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "invitaciones_grado"."django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "invitaciones_grado"."auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "invitaciones_grado"."django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "invitaciones_grado"."django_admin_log" ("user_id");
COMMIT;

-- admin.0002_logentry_remove_auto_add
BEGIN;
--
-- Alter field action_time on logentry
--
-- (no-op)
COMMIT;

-- admin.0003_logentry_add_action_flag_choices
BEGIN;
--
-- Alter field action_flag on logentry
--
-- (no-op)
COMMIT;

-- sessions.0001_initial
BEGIN;
--
-- Create model Session
--
CREATE TABLE "invitaciones_grado"."django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "invitaciones_grado"."django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "invitaciones_grado"."django_session" ("expire_date");
COMMIT;

-- ceremonies.0001_initial
BEGIN;
--
-- Create model Ceremony
--
CREATE TABLE "invitaciones_grado"."ceremonia" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "codigo" varchar(32) NOT NULL, "nombre" varchar(255) NOT NULL, "fecha_programada" timestamp with time zone NOT NULL, "lugar" varchar(255) NOT NULL, "estado" varchar(20) NOT NULL);
--
-- Create constraint uq_ceremonia_codigo on model ceremony
--
ALTER TABLE "invitaciones_grado"."ceremonia" ADD CONSTRAINT "uq_ceremonia_codigo" UNIQUE ("codigo");
CREATE INDEX "idx_ceremonia_est_fprog" ON "invitaciones_grado"."ceremonia" ("estado", "fecha_programada");
COMMIT;

-- accounts.0001_initial
BEGIN;
--
-- Create model ExternalIdentity
--
CREATE TABLE "invitaciones_grado"."identidad_externa" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "proveedor" varchar(20) NOT NULL, "issuer" varchar(255) NOT NULL, "subject" varchar(255) NOT NULL, "correo_electronico" varchar(254) NOT NULL, "claim_usuario" varchar(255) NOT NULL, "snapshot_claims" jsonb NOT NULL, "fecha_ultimo_inicio_sesion" timestamp with time zone NULL, "usuario_id" integer NOT NULL);
--
-- Create constraint uq_extid_prov_iss_sub on model externalidentity
--
ALTER TABLE "invitaciones_grado"."identidad_externa" ADD CONSTRAINT "uq_extid_prov_iss_sub" UNIQUE ("proveedor", "issuer", "subject");
ALTER TABLE "invitaciones_grado"."identidad_externa" ADD CONSTRAINT "identidad_externa_usuario_id_dd284d88_fk_auth_user_id" FOREIGN KEY ("usuario_id") REFERENCES "invitaciones_grado"."auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "identidad_externa_usuario_id_dd284d88" ON "invitaciones_grado"."identidad_externa" ("usuario_id");
CREATE INDEX "idx_extid_prov_email" ON "invitaciones_grado"."identidad_externa" ("proveedor", "correo_electronico");
COMMIT;

-- graduates.0001_initial
BEGIN;
--
-- Create model GraduateImportBatch
--
CREATE TABLE "invitaciones_grado"."lote_importacion_graduando" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "archivo_fuente" varchar(255) NOT NULL, "archivo_sha256" varchar(64) NOT NULL, "estado" varchar(20) NOT NULL, "filas_leidas" integer NOT NULL CHECK ("filas_leidas" >= 0), "filas_validas" integer NOT NULL CHECK ("filas_validas" >= 0), "filas_error" integer NOT NULL CHECK ("filas_error" >= 0), "graduandos_creados" integer NOT NULL CHECK ("graduandos_creados" >= 0), "graduandos_actualizados" integer NOT NULL CHECK ("graduandos_actualizados" >= 0), "invitaciones_creadas" integer NOT NULL CHECK ("invitaciones_creadas" >= 0), "resultado_validacion" jsonb NOT NULL, "detalle_fallo" text NOT NULL, "fecha_confirmacion" timestamp with time zone NULL, "ceremonia_id" integer NOT NULL, "usuario_confirmacion_id" integer NULL, "usuario_cargue_id" integer NULL);
--
-- Create model Graduate
--
CREATE TABLE "invitaciones_grado"."graduando" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "tipo_documento" varchar(20) NOT NULL, "codigo_estudiantil" varchar(32) NOT NULL, "numero_documento" varchar(32) NOT NULL, "nombre_completo" varchar(255) NOT NULL, "programa_academico" varchar(255) NOT NULL, "correo_electronico" varchar(254) NOT NULL, "cantidad_invitaciones" smallint NOT NULL CHECK ("cantidad_invitaciones" >= 0), "ceremonia_id" integer NOT NULL);
--
-- Create constraint ck_graduando_cant_inv on model graduate
--
ALTER TABLE "invitaciones_grado"."graduando" ADD CONSTRAINT "ck_graduando_cant_inv" CHECK ("cantidad_invitaciones" >= 0);
--
-- Create constraint uq_grad_cer_numdoc on model graduate
--
ALTER TABLE "invitaciones_grado"."graduando" ADD CONSTRAINT "uq_grad_cer_numdoc" UNIQUE ("ceremonia_id", "numero_documento");
--
-- Create constraint uq_grad_cer_codest on model graduate
--
CREATE UNIQUE INDEX "uq_grad_cer_codest" ON "invitaciones_grado"."graduando" ("ceremonia_id", "codigo_estudiantil") WHERE NOT ("codigo_estudiantil" = '');
ALTER TABLE "invitaciones_grado"."lote_importacion_graduando" ADD CONSTRAINT "lote_importacion_gra_ceremonia_id_2c39c916_fk_ceremonia" FOREIGN KEY ("ceremonia_id") REFERENCES "invitaciones_grado"."ceremonia" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."lote_importacion_graduando" ADD CONSTRAINT "lote_importacion_gra_usuario_confirmacion_a39f66f3_fk_auth_user" FOREIGN KEY ("usuario_confirmacion_id") REFERENCES "invitaciones_grado"."auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."lote_importacion_graduando" ADD CONSTRAINT "lote_importacion_gra_usuario_cargue_id_d4d06651_fk_auth_user" FOREIGN KEY ("usuario_cargue_id") REFERENCES "invitaciones_grado"."auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "lote_importacion_graduando_ceremonia_id_2c39c916" ON "invitaciones_grado"."lote_importacion_graduando" ("ceremonia_id");
CREATE INDEX "lote_importacion_graduando_usuario_confirmacion_id_a39f66f3" ON "invitaciones_grado"."lote_importacion_graduando" ("usuario_confirmacion_id");
CREATE INDEX "lote_importacion_graduando_usuario_cargue_id_d4d06651" ON "invitaciones_grado"."lote_importacion_graduando" ("usuario_cargue_id");
CREATE INDEX "idx_limp_cer_est_fcre" ON "invitaciones_grado"."lote_importacion_graduando" ("ceremonia_id", "estado", "fecha_creacion");
ALTER TABLE "invitaciones_grado"."graduando" ADD CONSTRAINT "graduando_ceremonia_id_982f8793_fk_ceremonia_id" FOREIGN KEY ("ceremonia_id") REFERENCES "invitaciones_grado"."ceremonia" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "graduando_ceremonia_id_982f8793" ON "invitaciones_grado"."graduando" ("ceremonia_id");
CREATE INDEX "idx_grad_numdoc" ON "invitaciones_grado"."graduando" ("numero_documento");
CREATE INDEX "idx_grad_codest" ON "invitaciones_grado"."graduando" ("codigo_estudiantil");
CREATE INDEX "idx_grad_cer_nom" ON "invitaciones_grado"."graduando" ("ceremonia_id", "nombre_completo");
COMMIT;

-- invitations.0001_initial
BEGIN;
--
-- Create model AccessPoint
--
CREATE TABLE "invitaciones_grado"."punto_acceso" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "codigo" varchar(32) NOT NULL, "nombre" varchar(100) NOT NULL, "descripcion" varchar(255) NOT NULL, "ceremonia_id" integer NOT NULL);
--
-- Create model Invitation
--
CREATE TABLE "invitaciones_grado"."invitacion" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "identificador_publico" uuid NOT NULL, "numero_invitacion" smallint NOT NULL CHECK ("numero_invitacion" >= 0), "codigo" varchar(64) NOT NULL, "version_token" smallint NOT NULL CHECK ("version_token" >= 0), "estado" varchar(20) NOT NULL, "fecha_envio" timestamp with time zone NULL, "fecha_uso" timestamp with time zone NULL, "fecha_anulacion" timestamp with time zone NULL, "etiqueta_dispositivo_uso" varchar(100) NOT NULL, "ip_validacion_exitosa" inet NULL, "graduando_id" integer NOT NULL, "punto_acceso_uso_id" integer NULL, "usuario_validador_id" integer NULL);
--
-- Create model ValidationLog
--
CREATE TABLE "invitaciones_grado"."registro_validacion" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "activo" boolean NOT NULL, "fecha_creacion" timestamp with time zone NOT NULL, "fecha_modificacion" timestamp with time zone NOT NULL, "huella_token" varchar(16) NOT NULL, "etiqueta_dispositivo" varchar(100) NOT NULL, "resultado" varchar(20) NOT NULL, "fecha_validacion" timestamp with time zone NOT NULL, "marcada_como_usada" boolean NOT NULL, "direccion_ip" inet NULL, "agente_usuario" text NOT NULL, "punto_acceso_id" integer NULL, "invitacion_id" integer NULL, "usuario_validador_id" integer NULL);
--
-- Create constraint ck_vlog_uso_req_inv on model validationlog
--
ALTER TABLE "invitaciones_grado"."registro_validacion" ADD CONSTRAINT "ck_vlog_uso_req_inv" CHECK ((NOT "marcada_como_usada" OR "invitacion_id" IS NOT NULL));
--
-- Create index idx_inv_grad_est on field(s) graduate, status of model invitation
--
CREATE INDEX "idx_inv_grad_est" ON "invitaciones_grado"."invitacion" ("graduando_id", "estado");
--
-- Create index idx_inv_est_fuso on field(s) status, used_at of model invitation
--
CREATE INDEX "idx_inv_est_fuso" ON "invitaciones_grado"."invitacion" ("estado", "fecha_uso");
--
-- Create constraint ck_inv_numero on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "ck_inv_numero" CHECK ("numero_invitacion" >= 1);
--
-- Create constraint ck_inv_version on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "ck_inv_version" CHECK ("version_token" >= 1);
--
-- Create constraint uq_inv_pubid on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "uq_inv_pubid" UNIQUE ("identificador_publico");
--
-- Create constraint uq_inv_codigo on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "uq_inv_codigo" UNIQUE ("codigo");
--
-- Create constraint uq_inv_grad_num on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "uq_inv_grad_num" UNIQUE ("graduando_id", "numero_invitacion");
--
-- Create constraint ck_inv_estado_fech on model invitation
--
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "ck_inv_estado_fech" CHECK ((("estado" = 'used' AND "fecha_uso" IS NOT NULL AND "fecha_anulacion" IS NULL) OR ("estado" = 'cancelled' AND "fecha_anulacion" IS NOT NULL AND "fecha_uso" IS NULL) OR ("estado" IN ('created', 'sent') AND "fecha_uso" IS NULL AND "fecha_anulacion" IS NULL)));
--
-- Create index idx_ptacc_cer_act on field(s) ceremony, is_active of model accesspoint
--
CREATE INDEX "idx_ptacc_cer_act" ON "invitaciones_grado"."punto_acceso" ("ceremonia_id", "activo");
--
-- Create constraint uq_ptacc_cer_codigo on model accesspoint
--
ALTER TABLE "invitaciones_grado"."punto_acceso" ADD CONSTRAINT "uq_ptacc_cer_codigo" UNIQUE ("ceremonia_id", "codigo");
ALTER TABLE "invitaciones_grado"."punto_acceso" ADD CONSTRAINT "punto_acceso_ceremonia_id_72aeed4e_fk_ceremonia_id" FOREIGN KEY ("ceremonia_id") REFERENCES "invitaciones_grado"."ceremonia" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "punto_acceso_ceremonia_id_72aeed4e" ON "invitaciones_grado"."punto_acceso" ("ceremonia_id");
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "invitacion_graduando_id_70ffb4f4_fk_graduando_id" FOREIGN KEY ("graduando_id") REFERENCES "invitaciones_grado"."graduando" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "invitacion_punto_acceso_uso_id_76e8fc29_fk_punto_acceso_id" FOREIGN KEY ("punto_acceso_uso_id") REFERENCES "invitaciones_grado"."punto_acceso" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."invitacion" ADD CONSTRAINT "invitacion_usuario_validador_id_bf8517ce_fk_auth_user_id" FOREIGN KEY ("usuario_validador_id") REFERENCES "invitaciones_grado"."auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "invitacion_graduando_id_70ffb4f4" ON "invitaciones_grado"."invitacion" ("graduando_id");
CREATE INDEX "invitacion_punto_acceso_uso_id_76e8fc29" ON "invitaciones_grado"."invitacion" ("punto_acceso_uso_id");
CREATE INDEX "invitacion_usuario_validador_id_bf8517ce" ON "invitaciones_grado"."invitacion" ("usuario_validador_id");
ALTER TABLE "invitaciones_grado"."registro_validacion" ADD CONSTRAINT "registro_validacion_punto_acceso_id_9ef1b57a_fk_punto_acceso_id" FOREIGN KEY ("punto_acceso_id") REFERENCES "invitaciones_grado"."punto_acceso" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."registro_validacion" ADD CONSTRAINT "registro_validacion_invitacion_id_31d99b9c_fk_invitacion_id" FOREIGN KEY ("invitacion_id") REFERENCES "invitaciones_grado"."invitacion" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "invitaciones_grado"."registro_validacion" ADD CONSTRAINT "registro_validacion_usuario_validador_id_4b24951c_fk_auth_user" FOREIGN KEY ("usuario_validador_id") REFERENCES "invitaciones_grado"."auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "registro_validacion_punto_acceso_id_9ef1b57a" ON "invitaciones_grado"."registro_validacion" ("punto_acceso_id");
CREATE INDEX "registro_validacion_invitacion_id_31d99b9c" ON "invitaciones_grado"."registro_validacion" ("invitacion_id");
CREATE INDEX "registro_validacion_usuario_validador_id_4b24951c" ON "invitaciones_grado"."registro_validacion" ("usuario_validador_id");
CREATE INDEX "idx_vlog_huella" ON "invitaciones_grado"."registro_validacion" ("huella_token");
CREATE INDEX "idx_vlog_inv_fval" ON "invitaciones_grado"."registro_validacion" ("invitacion_id", "fecha_validacion");
CREATE INDEX "idx_vlog_res_fval" ON "invitaciones_grado"."registro_validacion" ("resultado", "fecha_validacion");
CREATE INDEX "idx_vlog_usr_fval" ON "invitaciones_grado"."registro_validacion" ("usuario_validador_id", "fecha_validacion");
CREATE INDEX "idx_vlog_pacc_fval" ON "invitaciones_grado"."registro_validacion" ("punto_acceso_id", "fecha_validacion");
COMMIT;

-- django_migrations
BEGIN;
CREATE TABLE IF NOT EXISTS "invitaciones_grado"."django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL);
INSERT INTO "invitaciones_grado"."django_migrations" ("app", "name", "applied")
VALUES
    ('contenttypes', '0001_initial', '2026-06-10T20:52:07.846858+00:00'),
    ('contenttypes', '0002_remove_content_type_name', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0001_initial', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0002_alter_permission_name_max_length', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0003_alter_user_email_max_length', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0004_alter_user_username_opts', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0005_alter_user_last_login_null', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0006_require_contenttypes_0002', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0007_alter_validators_add_error_messages', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0008_alter_user_username_max_length', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0009_alter_user_last_name_max_length', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0010_alter_group_name_max_length', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0011_update_proxy_permissions', '2026-06-10T20:52:07.846858+00:00'),
    ('auth', '0012_alter_user_first_name_max_length', '2026-06-10T20:52:07.846858+00:00'),
    ('admin', '0001_initial', '2026-06-10T20:52:07.846858+00:00'),
    ('admin', '0002_logentry_remove_auto_add', '2026-06-10T20:52:07.846858+00:00'),
    ('admin', '0003_logentry_add_action_flag_choices', '2026-06-10T20:52:07.846858+00:00'),
    ('sessions', '0001_initial', '2026-06-10T20:52:07.846858+00:00'),
    ('core', '0001_initial', '2026-06-10T20:52:07.846858+00:00'),
    ('ceremonies', '0001_initial', '2026-06-10T20:52:07.846858+00:00'),
    ('accounts', '0001_initial', '2026-06-10T20:52:07.846858+00:00'),
    ('graduates', '0001_initial', '2026-06-10T20:52:07.846858+00:00'),
    ('invitations', '0001_initial', '2026-06-10T20:52:07.846858+00:00');
SELECT setval(pg_get_serial_sequence('"invitaciones_grado"."django_migrations"', 'id'), COALESCE((SELECT MAX("id") FROM "invitaciones_grado"."django_migrations"), 1), true);
COMMIT;

-- Metadatos base de Django
BEGIN;
INSERT INTO "invitaciones_grado"."django_content_type" ("id", "app_label", "model")
VALUES
    (1, 'contenttypes', 'contenttype'),
    (2, 'auth', 'group'),
    (3, 'auth', 'permission'),
    (4, 'auth', 'user'),
    (5, 'admin', 'logentry'),
    (6, 'sessions', 'session'),
    (7, 'ceremonies', 'ceremony'),
    (8, 'accounts', 'externalidentity'),
    (9, 'graduates', 'graduate'),
    (10, 'graduates', 'graduateimportbatch'),
    (11, 'invitations', 'accesspoint'),
    (12, 'invitations', 'invitation'),
    (13, 'invitations', 'validationlog');
SELECT setval(pg_get_serial_sequence('"invitaciones_grado"."django_content_type"', 'id'), COALESCE((SELECT MAX("id") FROM "invitaciones_grado"."django_content_type"), 1), true);
INSERT INTO "invitaciones_grado"."auth_permission" ("id", "name", "content_type_id", "codename")
VALUES
    (1, 'Can add content type', 1, 'add_contenttype'),
    (2, 'Can change content type', 1, 'change_contenttype'),
    (3, 'Can delete content type', 1, 'delete_contenttype'),
    (4, 'Can view content type', 1, 'view_contenttype'),
    (5, 'Can add group', 2, 'add_group'),
    (6, 'Can change group', 2, 'change_group'),
    (7, 'Can delete group', 2, 'delete_group'),
    (8, 'Can view group', 2, 'view_group'),
    (9, 'Can add permission', 3, 'add_permission'),
    (10, 'Can change permission', 3, 'change_permission'),
    (11, 'Can delete permission', 3, 'delete_permission'),
    (12, 'Can view permission', 3, 'view_permission'),
    (13, 'Can add user', 4, 'add_user'),
    (14, 'Can change user', 4, 'change_user'),
    (15, 'Can delete user', 4, 'delete_user'),
    (16, 'Can view user', 4, 'view_user'),
    (17, 'Can add log entry', 5, 'add_logentry'),
    (18, 'Can change log entry', 5, 'change_logentry'),
    (19, 'Can delete log entry', 5, 'delete_logentry'),
    (20, 'Can view log entry', 5, 'view_logentry'),
    (21, 'Can add session', 6, 'add_session'),
    (22, 'Can change session', 6, 'change_session'),
    (23, 'Can delete session', 6, 'delete_session'),
    (24, 'Can view session', 6, 'view_session'),
    (25, 'Can add ceremonia', 7, 'add_ceremony'),
    (26, 'Can change ceremonia', 7, 'change_ceremony'),
    (27, 'Can delete ceremonia', 7, 'delete_ceremony'),
    (28, 'Can view ceremonia', 7, 'view_ceremony'),
    (29, 'Can add identidad externa', 8, 'add_externalidentity'),
    (30, 'Can change identidad externa', 8, 'change_externalidentity'),
    (31, 'Can delete identidad externa', 8, 'delete_externalidentity'),
    (32, 'Can view identidad externa', 8, 'view_externalidentity'),
    (33, 'Can add graduando', 9, 'add_graduate'),
    (34, 'Can change graduando', 9, 'change_graduate'),
    (35, 'Can delete graduando', 9, 'delete_graduate'),
    (36, 'Can view graduando', 9, 'view_graduate'),
    (37, 'Can add lote de importacion de graduandos', 10, 'add_graduateimportbatch'),
    (38, 'Can change lote de importacion de graduandos', 10, 'change_graduateimportbatch'),
    (39, 'Can delete lote de importacion de graduandos', 10, 'delete_graduateimportbatch'),
    (40, 'Can view lote de importacion de graduandos', 10, 'view_graduateimportbatch'),
    (41, 'Can add punto de acceso', 11, 'add_accesspoint'),
    (42, 'Can change punto de acceso', 11, 'change_accesspoint'),
    (43, 'Can delete punto de acceso', 11, 'delete_accesspoint'),
    (44, 'Can view punto de acceso', 11, 'view_accesspoint'),
    (45, 'Can add invitacion', 12, 'add_invitation'),
    (46, 'Can change invitacion', 12, 'change_invitation'),
    (47, 'Can delete invitacion', 12, 'delete_invitation'),
    (48, 'Can view invitacion', 12, 'view_invitation'),
    (49, 'Can add registro de validacion', 13, 'add_validationlog'),
    (50, 'Can change registro de validacion', 13, 'change_validationlog'),
    (51, 'Can delete registro de validacion', 13, 'delete_validationlog'),
    (52, 'Can view registro de validacion', 13, 'view_validationlog');
SELECT setval(pg_get_serial_sequence('"invitaciones_grado"."auth_permission"', 'id'), COALESCE((SELECT MAX("id") FROM "invitaciones_grado"."auth_permission"), 1), true);
COMMIT;
